# Generated by Django 2.1.5 on 2019-02-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_uploadfile_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='email',
        ),
    ]
