# Generated by Django 2.1.5 on 2019-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190219_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='projectName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
