# Generated by Django 2.1.5 on 2019-02-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
