# Generated by Django 2.1.5 on 2019-02-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190213_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='text',
        ),
    ]
