# Generated by Django 2.1.5 on 2019-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_uploadfile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='projectFile',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='projectName',
            field=models.TextField(default=''),
        ),
    ]
