# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'To do'), (1, 'Done')], default=0)),
            ],
        ),
    ]
